server:
  port: ":8080"
  environment: "development"

database:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "flower_shop"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  prefix: "flower_shop:"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  use_ssl: false
  bucket: "flower-shop"
  location: "us-east-1"

jwt:
  secret: "your-secret-key-here"
  expires_in: 72 # hours

wechat:
  app_id: "your-app-id-here"
  app_secret: "your-app-secret-here"

upload:
  save_path: "./uploads"
  max_size: 5242880 # 5MB

logger:
  level: "info"  # debug, info, warn, error, fatal
  encoding: "json"  # json or console
  output_path: "stdout"  # stdout or file path 